### PR TITLE
All SVG tags.

### PR DESCRIPTION
**Pull request by KonZee**
Is there way to prevent writing tons of similar code like this? 
https://github.com/KonZee/nitro/blob/master/src/elements/element_animate.erl#L51
https://github.com/KonZee/nitro/blob/master/src/elements/element_animatemotion.erl#L54
https://github.com/KonZee/nitro/blob/master/src/elements/element_animatetransform.erl#L52

### CODE REVIEW

**Comment by KonZee** [comment]
Add requested tags

**Comment by KonZee** [comment]
All SVG tags.

**Comment by 5HT** [comment]
Could you move all those elements to `svg` folder, like `src/svg/element_*.erl`?

**Comment by KonZee** [comment]
Done.

**Comment by 5HT** [comment]
Well done, thanks.

**Pull request merged**
