### PR TITLE
Template tag, basic SVG support

### PR DESCRIPTION
**Pull request by KonZee**
1. Add <template> tag.
2. Add macros for SVG, defined by svg attribute groups.
3. Add element_svg and element_animate. As root elements they also contain functions with attributes lists by attribute groups.

### CODE REVIEW

**Comment by 5HT** [comment]
Do you have an example application for this change?

**Comment by KonZee** [comment]
I'm sorry, but I didn't test enought and will make some fixes soon. Pre/postprocessors helpfull tools, but distrupt ability to testing and check syntax.

I have working local app based on n2o/samples. Template and svg tags output correct, animate have a problem and will be removed for this time.

**Comment by 5HT** [comment]
If it's possible I just want to take a look onto your SVG app. So I would suggest anything.
Once we did SVG app: http://ns.synrc.com:8080/static/app/index.htm

**Comment by KonZee** [comment]
> If it's possible I just want to take a look onto your SVG app.

I wouldn't call it "my app" : ) Technically, it's just some additional line of code for new tags in the your samples login.erl and these new files in nitro. Here's an example: http://104.131.55.204:8000/

``` Erlang
   #template{id="tpl"},
   #panel{body="SVG test"},
   #svg{id="svg-test", fill="#00FF00", body=[#animate{id="animate"}, "<circle cx='40' cy='40' r='40'>"]}
```

> So I would suggest anything.
> Once we did SVG app: http://ns.synrc.com:8080/static/app/index.htm

Yes, I read about it in your LJ. But my point of view is rather simple, and I'm not sure if/how it meets your proposal.

Currently I'm working front-end developer and I'm actively using inline SVG in HTML markup. And SVG tags in Nitro seems like as useful feature. Mayby I'm wrong at that and it's useful only for me, in with case it's  better to output svg as part of body of container. Or maybe one needs to make another poject with svg tags only.
But I'm also trying to think ahead. I want to extend my scope to fullstack and I put my bet on Erlang for Web. You probably can answer the question "Why Erlang?" a hundred times better than I would.  And Nitro is simple enough to learn and handle, to make something useful for other users and to improve my skill.
Shotly speaking,  I'm trying to learn Erlang while using my current competence. If your suggestions help at it, I can take it.

**Comment by 5HT** [comment]
SVG is something really useful, no matter it would be in `nitro` or as separate `svg` application. For sure SVG elements need `circle`, `g`, `rect`, `path`, `text`, `tspan` low level primitives but also (as we think of `nitro` as presentation layer) its own SVG versions of `textarea`, `table`, `button`, `input` etc. Having full GUI set of control elements in SVG would be a kickass project. They could be cartoonized for games not styled as for business applications. It should be really useful for 2D interactive projects, attractive but simple animations reach.

**Pull request merged**
